export type Listing = {
    id: number;
    title: string;
    description: string;
    plant_category: string;
    company_name: string;
    contact_email: string;
    phone_number: string;
    website: string | null;
    hire_rate_gbp: string;
    hire_rate_eur: string;
    hire_rate_usd: string;
    hire_rate_aud: string;
    hire_rate_nzd: string;
    hire_rate_zar: string;
    tags: string[];
    company_logo: string[] | null;
    photo_gallery: string[] | null;
    attachments: string[] | null;
    social_networks: string[] | null;
    location: string;
    latitude: number;
    longitude: number;
    region: string;
    related_listing: number[] | null;
    hire_rental: string | null;
    additional_1: string | null;
    additional_2: string | null;
    additional_3: string | null;
    additional_4: string | null;
    additional_5: string | null;
    additional_6: string | null;
    additional_7: string | null;
    additional_8: string | null;
    additional_9: string | null;
    additional_10: string | null;
    created_at: string;
    updated_at: string;
};

export type ListingFormData = {
    title: string;
    description: string;
    plant_category: string;
    contact_email: string;
    phone_number: string;
    website: string | null;
    hire_rate_gbp: string;
    hire_rate_eur: string;
    hire_rate_usd: string;
    hire_rate_aud: string;
    hire_rate_nzd: string;
    hire_rate_zar: string;
    tags: string[];
    company_logo: string | null;
    photo_gallery: string[] | [null];
    attachments: string[] | [null];
    social_networks: string[] | [null];
    location: string;
    latitude: number;
    longitude: number;
    region: string;
    related_listing: string[] | [null];
    hire_rental: string | null;
    additional_1: string | null;
    additional_2: string | null;
    additional_3: string | null;
    additional_4: string | null;
    additional_5: string | null;
    additional_6: string | null;
    additional_7: string | null;
    additional_8: string | null;
    additional_9: string | null;
    additional_10: string | null;
};
